import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class PokemonService {

  constructor() { }

  pokemon : any[] = [
    {
    "id": 1,
    "name": "Bulbizarre",
    "tagline": "A Real Bitter Experience.",
    "first_brewed": "09/2007",
    "description": "A light, crisp and bitter IPA brewed with English and American hops. A small batch brewed only once.",
    "image_url": "https://www.pokepedia.fr/images/e/ef/Bulbizarre-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/4/4e/Miniature_001_LGPE.png",
    "abv": 4.5,
    "ibu": 60,
    "target_fg": 1010,
    "target_og": 1044,
    "ebc": 20,
    "srm": 10,
    "ph": 4.4,
    "attenuation_level": 75,
    },
    {
    "id": 2,
    "name": "Herbizarre",
    "tagline": "You Know You Shouldn't",
    "first_brewed": "04/2008",
    "description": "A titillating, neurotic, peroxide punk of a Pale Ale. Combining attitude, style, substance, and a little bit of low self esteem for good measure; what would your mother say? The seductive lure of the sassy passion fruit hop proves too much to resist. All that is even before we get onto the fact that there are no additives, preservatives, pasteurization or strings attached. All wrapped up with the customary BrewDog bite and imaginative twist.",
    "image_url": "https://www.pokepedia.fr/images/4/44/Herbizarre-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/f/fb/Miniature_002_LGPE.png",
    "abv": 4.1,
    "ibu": 41.5,
    "target_fg": 1010,
    "target_og": 1041.7,
    "ebc": 15,
    "srm": 15,
    "ph": 4.4,
    "attenuation_level": 76,
    },
    {
    "id": 3,
    "name": "Berliner Weisse With Yuzu - B-Sides",
    "tagline": "Japanese Citrus Berliner Weisse.",
    "first_brewed": "11/2015",
    "description": "Japanese citrus fruit intensifies the sour nature of this German classic.",
    "image_url": "https://www.pokepedia.fr/images/4/42/Florizarre-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/6/60/Miniature_003_LGPE.png",
    "abv": 4.2,
    "ibu": 8,
    "target_fg": 1007,
    "target_og": 1040,
    "ebc": 8,
    "srm": 4,
    "ph": 3.2,
    "attenuation_level": 83,
    },
    {
    "id": 4,
    "name": "Pilsen Lager",
    "tagline": "Unleash the Yeast Series.",
    "first_brewed": "09/2013",
    "description": "Our Unleash the Yeast series was an epic experiment into the differences in aroma and flavour provided by switching up your yeast. We brewed up a wort with a light caramel note and some toasty biscuit flavour, and hopped it with Amarillo and Centennial for a citrusy bitterness. Everything else is down to the yeast. Pilsner yeast ferments with no fruity esters or spicy phenols, although it can add a hint of butterscotch.",
    "image_url": "https://www.pokepedia.fr/images/8/89/Salamèche-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/8/89/Miniature_004_LGPE.png",
    "abv": 6.3,
    "ibu": 55,
    "target_fg": 1012,
    "target_og": 1060,
    "ebc": 30,
    "srm": 15,
    "ph": 4.4,
    "attenuation_level": 80,
    },
    {
    "id": 5,
    "name": "Avery Brown Dredge",
    "tagline": "Bloggers' Imperial Pilsner.",
    "first_brewed": "02/2011",
    "description": "An Imperial Pilsner in collaboration with beer writers. Tradition. Homage. Revolution. We wanted to showcase the awesome backbone of the Czech brewing tradition, the noble Saaz hop, and also tip our hats to the modern beers that rock our world, and the people who make them.",
    "image_url": "https://www.pokepedia.fr/images/6/64/Reptincel-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/3/35/Miniature_005_LGPE.png",
    "abv": 7.2,
    "ibu": 59,
    "target_fg": 1027,
    "target_og": 1069,
    "ebc": 10,
    "srm": 5,
    "ph": 4.4,
    "attenuation_level": 67,
    },
    {
    "id": 6,
    "name": "Electric India",
    "tagline": "Vibrant Hoppy Saison.",
    "first_brewed": "05/2013",
    "description": "Re-brewed as a spring seasonal, this beer – which appeared originally as an Equity Punk shareholder creation – retains its trademark spicy, fruity edge. A perfect blend of Belgian Saison and US IPA, crushed peppercorns and heather honey are also added to produce a genuinely unique beer.",
    "image_url": "https://www.pokepedia.fr/images/1/17/Dracaufeu-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/6/68/Miniature_006_LGPE.png",
    "abv": 5.2,
    "ibu": 38,
    "target_fg": 1005,
    "target_og": 1045,
    "ebc": 15,
    "srm": 7.5,
    "ph": 4.4,
    "attenuation_level": 88.9,
    },
    {
    "id": 7,
    "name": "AB:12",
    "tagline": "Imperial Black Belgian Ale.",
    "first_brewed": "07/2012",
    "description": "An Imperial Black Belgian Ale aged in old Invergordon Scotch whisky barrels with mountains of raspberries, tayberries and blackberries in each cask. Decadent but light and dry, this beer would make a fantastic base for ageing on pretty much any dark fruit - we used raspberries, tayberries and blackberries beause they were local.",
    "image_url": "https://www.pokepedia.fr/images/c/cc/Carapuce-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/9/95/Miniature_007_LGPE.png",
    "abv": 11.2,
    "ibu": 35,
    "target_fg": 1017,
    "target_og": 1108,
    "ebc": 80,
    "srm": 40,
    "ph": 5.3,
    "attenuation_level": 84,
    },
    {
    "id": 8,
    "name": "Fake Lager",
    "tagline": "Bohemian Pilsner.",
    "first_brewed": "03/2013",
    "description": "Fake is the new black. Fake is where it is at. Fake Art, fake brands, fake breasts, and fake lager. We want to play our part in the ugly fallout from the Lager Dream. Say hello to Fake Lager – a zesty, floral 21st century faux masterpiece with added BrewDog bitterness.",
    "image_url": "https://www.pokepedia.fr/images/2/2a/Carabaffe-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/b/b6/Miniature_008_LGPE.png",
    "abv": 4.7,
    "ibu": 40,
    "target_fg": 1010,
    "target_og": 1046,
    "ebc": 12,
    "srm": 6,
    "ph": 4.4,
    "attenuation_level": 78,
    },
    {
    "id": 9,
    "name": "AB:07",
    "tagline": "Whisky Cask-Aged Scotch Ale.",
    "first_brewed": "03/2010",
    "description": "Whisky cask-aged imperial scotch ale. Beer perfect for when the rain is coming sideways. Liquorice, plum and raisin temper the warming alcohol, producing a beer capable of holding back the Scottish chill.",
    "image_url": "https://www.pokepedia.fr/images/2/24/Tortank-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/7/73/Miniature_009_LGPE.png",
    "abv": 12.5,
    "ibu": 30,
    "target_fg": 1020,
    "target_og": 1106,
    "ebc": 84,
    "srm": 42,
    "ph": 5.6,
    "attenuation_level": 83,
    },
    {
    "id": 10,
    "name": "Bramling X",
    "tagline": "Single Hop IPA Series - 2011.",
    "first_brewed": "01/2011",
    "description": "Good old Bramling Cross is elegant, refined, assured, (boring) and understated. Understated that is unless you hop the living daylights out of a beer with it. This is Bramling Cross re-invented and re-imagined, and shows just what can be done with English hops if you use enough of them. Poor Bramling Cross normally gets lost in a woeful stream of conformist brown ales made by sleepy cask ale brewers. But not anymore. This beer shows that British hops do have some soul, and is a fruity riot of blackberries, pears, and plums. Reminds me of the bramble, apple and ginger jam my grandmother used to make.",
    "image_url": "https://www.pokepedia.fr/images/c/c7/Chenipan-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/1/11/Miniature_010_LGPE.png",
    "abv": 7.5,
    "ibu": 75,
    "target_fg": 1013,
    "target_og": 1068,
    "ebc": 22,
    "srm": 11,
    "ph": 4.4,
    "attenuation_level": 80.9,
    },
    {
    "id": 11,
    "name": "Misspent Youth",
    "tagline": "Milk & Honey Scotch Ale.",
    "first_brewed": "04/2013",
    "description": "The brainchild of our small batch brewer, George Woods. A dangerously drinkable milk sugar- infused Scotch Ale.",
    "image_url": "https://www.pokepedia.fr/images/6/6c/Chrysacier-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/a/af/Miniature_011_LGPE.png",
    "abv": 7.3,
    "ibu": 30,
    "target_fg": 1020,
    "target_og": 1079,
    "ebc": 120,
    "srm": 60,
    "ph": 4.4,
    "attenuation_level": 74.7,
    },
    {
    "id": 12,
    "name": "Arcade Nation",
    "tagline": "Seasonal Black IPA.",
    "first_brewed": "12/2015",
    "description": "Running the knife-edge between an India Pale Ale and a Stout, this particular style is one we truly love. Black IPAs are a great showcase for the skill of our brew team, balancing so many complex and twisting flavours in the same moment. The citrus, mango and pine from the hops – three of our all-time favourites – play off against the roasty dryness from the malt bill at each and every turn.",
    "image_url": "https://www.pokepedia.fr/images/8/83/Papilusion-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/5/5e/Miniature_012_EB.png",
    "abv": 5.3,
    "ibu": 60,
    "target_fg": 1012,
    "target_og": 1052,
    "ebc": 200,
    "srm": 100,
    "ph": 4.2,
    "attenuation_level": 77,
    },
    {
    "id": 13,
    "name": "Movember",
    "tagline": "Moustache-Worthy Beer.",
    "first_brewed": "11/2009",
    "description": "A deliciously robust, black malted beer with a decadent dark, dry cocoa flavour that provides an enticing backdrop to the Cascade hops.",
    "image_url": "https://www.pokepedia.fr/images/9/9b/Aspicot-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/c/cb/Miniature_013_LGPE.png",
    "abv": 4.5,
    "ibu": 50,
    "target_fg": 1012,
    "target_og": 1047,
    "ebc": 140,
    "srm": 70,
    "ph": 5.2,
    "attenuation_level": 74.5,
    },
    {
    "id": 14,
    "name": "Alpha Dog",
    "tagline": "Existential Red Ale.",
    "first_brewed": "02/2010",
    "description": "A fusion of caramel malt flavours and punchy New Zealand hops. A session beer you can get your teeth into.",
    "image_url": "https://www.pokepedia.fr/images/b/b6/Coconfort-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/f/fd/Miniature_014_LGPE.png",
    "abv": 4.5,
    "ibu": 42,
    "target_fg": 1025,
    "target_og": 1046,
    "ebc": 62,
    "srm": 31,
    "ph": 4.4,
    "attenuation_level": 72.8,
    },
    {
    "id": 15,
    "name": "Mixtape 8",
    "tagline": "An Epic Fusion Of Old Belgian, American New Wave, And Scotch Whisky.",
    "first_brewed": "01/2012",
    "description": "This recipe is for the Belgian Tripel base. A blend of two huge oak aged beers – half a hopped up Belgian Tripel, and half a Triple India Pale Ale. Both aged in single grain whisky barrels for two years and blended, each beer brings its own character to the mix. The Belgian Tripel comes loaded with complex spicy, fruity esters, and punchy citrus hop character.",
    "image_url": "https://www.pokepedia.fr/images/e/ee/Dardargnan-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/c/c9/Miniature_015_LGPE.png",
    "abv": 14.5,
    "ibu": 50,
    "target_fg": 1014,
    "target_og": 1093,
    "ebc": 40,
    "srm": 20,
    "ph": 4.4,
    "attenuation_level": 85,
    },
    {
    "id": 16,
    "name": "Libertine Porter",
    "tagline": "Dry-Hopped Aggressive Porter.",
    "first_brewed": "01/2012",
    "description": "An avalanche of cross-continental hop varieties give this porter a complex spicy, resinous and citrusy aroma, with a huge malt bill providing a complex roasty counterpoint. Digging deeper into the flavour draws out cinder toffee, bitter chocolate and hints of woodsmoke.",
    "image_url": "https://www.pokepedia.fr/images/9/94/Roucool-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/a/ad/Miniature_016_LGPE.png",
    "abv": 6.1,
    "ibu": 45,
    "target_fg": 1020,
    "target_og": 1067,
    "ebc": 219,
    "srm": 109.5,
    "ph": 4.4,
    "attenuation_level": 70.1,
    },
    {
    "id": 17,
    "name": "AB:06",
    "tagline": "Imperial Black IPA.",
    "first_brewed": "04/2011",
    "description": "Our sixth Abstrakt, this imperial black IPA combined dark malts with a monumental triple dry-hop, using an all-star team of some of our favourite American hops. Roasty and resinous.",
    "image_url": "https://www.pokepedia.fr/images/d/dc/Roucoups-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/5/54/Miniature_017_LGPE.png",
    "abv": 11.2,
    "ibu": 150,
    "target_fg": 1013,
    "target_og": 1098,
    "ebc": 70,
    "srm": 35,
    "ph": null,
    "attenuation_level": 87,
    },
    {
    "id": 18,
    "name": "Russian Doll – India Pale Ale",
    "tagline": "Nesting Hop Bomb.",
    "first_brewed": "08/2014",
    "description": "The levels of hops vary throughout the range. We love hops, so all four beers are big, bitter badasses, but by tweaking the amount of each hop used later in the boil and during dry- hopping, we can balance the malty backbone with some unexpected flavours. Simcoe is used in the whirlpool for all four beers, and yet still lends different characters to each",
    "image_url": "https://www.pokepedia.fr/images/d/d8/Roucarnage-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/b/b6/Miniature_018_LGPE.png",
    "abv": 6,
    "ibu": 70,
    "target_fg": 1012,
    "target_og": 1058,
    "ebc": 25,
    "srm": 12.5,
    "ph": 5.2,
    "attenuation_level": 79.3,
    },
    {
    "id": 19,
    "name": "Hello My Name Is Mette-Marit",
    "tagline": "Lingonberry Double IPA.",
    "first_brewed": "06/2013",
    "description": "We sent this beer to Norway where it was known as 'Hello, my name is Censored’. You can make up your own mind as to why. This brew was a red berry explosion, with a reisnous bitter edge layered with dry berry tartness.",
    "image_url": "https://www.pokepedia.fr/images/9/9e/Rattata-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/7/7d/Miniature_019_LGPE.png",
    "abv": 8.2,
    "ibu": 70,
    "target_fg": 1013,
    "target_og": 1076,
    "ebc": null,
    "srm": null,
    "ph": 4.4,
    "attenuation_level": 83,
    },
    {
    "id": 20,
    "name": "Rabiator",
    "tagline": "Imperial Wheat Beer",
    "first_brewed": "03/2011",
    "description": "Imperial Wheat beer / Weizenbock brewed by a homesick German in leather trousers. Think banana bread, bubble gum and David Hasselhoff.",
    "image_url": "https://www.pokepedia.fr/images/9/98/Rattatac-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/9/93/Miniature_020_LGPE.png",
    "abv": 10.27,
    "ibu": 26,
    "target_fg": 1014,
    "target_og": 1092,
    "ebc": 24,
    "srm": 12,
    "ph": 4.4,
    "attenuation_level": 85,
    },
    {
    "id": 21,
    "name": "Vice Bier",
    "tagline": "Hoppy Wheat Bier.",
    "first_brewed": "04/2013",
    "description": "Our take on the classic German Kristallweizen. A clear German wheat beer, layers of bubblegum and vanilla perfectly balanced with the American and New Zealand hops.",
    "image_url": "https://www.pokepedia.fr/images/7/7d/Piafabec-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/b/b1/Miniature_021_LGPE.png",
    "abv": 4.3,
    "ibu": 25,
    "target_fg": 1010,
    "target_og": 1043,
    "ebc": 30,
    "srm": 15,
    "ph": 4,
    "attenuation_level": 81.8,
    },
    {
    "id": 22,
    "name": "Devine Rebel (w/ Mikkeller)",
    "tagline": "Oak-aged Barley Wine.",
    "first_brewed": "12/2008",
    "description": "Two of Europe's most experimental, boundary-pushing brewers, BrewDog and Mikkeller, combined forces to produce a rebellious beer that combined their respective talents and brewing skills. The 12.5% Barley Wine fermented well, and the champagne yeast drew it ever closer to 12.5%. The beer was brewed with a single hop variety and was going to be partially aged in oak casks.",
    "image_url": "https://www.pokepedia.fr/images/f/f2/Rapasdepic-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/8/89/Miniature_022_LGPE.png",
    "abv": 12.5,
    "ibu": 100,
    "target_fg": 1030,
    "target_og": 1093,
    "ebc": 36,
    "srm": 18,
    "ph": 4.4,
    "attenuation_level": 68,
    },
    {
    "id": 23,
    "name": "Storm",
    "tagline": "Islay Whisky Aged IPA.",
    "first_brewed": "12/2007",
    "description": "Dark and powerful Islay magic infuses this tropical sensation of an IPA. Using the original Punk IPA as a base, we boosted the ABV to 8% giving it some extra backbone to stand up to the peated smoke imported directly from Islay.",
    "image_url": "https://www.pokepedia.fr/images/5/56/Abo-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/8/87/Miniature_023_LGPE.png",
    "abv": 8,
    "ibu": 60,
    "target_fg": 1010,
    "target_og": 1082,
    "ebc": 12,
    "srm": 6,
    "ph": 4.4,
    "attenuation_level": 86,
    },
    {
    "id": 24,
    "name": "The End Of History",
    "tagline": "The World's Strongest Beer.",
    "first_brewed": "06/2011",
    "description": "The End of History: The name derives from the famous work of philosopher Francis Fukuyama, this is to beer what democracy is to history. Complexity defined. Floral, grapefruit, caramel and cloves are intensified by boozy heat.",
    "image_url": "https://www.pokepedia.fr/images/7/7f/Arbok-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/9/97/Miniature_024_LGPE.png",
    "abv": 55,
    "ibu": null,
    "target_fg": 1000,
    "target_og": 1112,
    "ebc": null,
    "srm": null,
    "ph": 4.4,
    "attenuation_level": 100,
    },
    {
    "id": 25,
    "name": "Bad Pixie",
    "tagline": "Spiced Wheat Beer.",
    "first_brewed": "10/2008",
    "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
    "image_url": "https://www.pokepedia.fr/images/7/76/Pikachu-DEPS.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/d/d6/Miniature_025_LGPE.png",
    "abv": 4.7,
    "ibu": 45,
    "target_fg": 1010,
    "target_og": 1047,
    "ebc": 8,
    "srm": 4,
    "ph": 4.4,
    "attenuation_level": 79,
    },
    {
    "id": 26,
    "name": "Bad Pixie",
    "tagline": "Spiced Wheat Beer.",
    "first_brewed": "10/2008",
    "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
    "image_url": "https://www.pokepedia.fr/images/7/7d/Raichu-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/6/6f/Miniature_026_EB.png",
    "abv": 4.7,
    "ibu": 45,
    "target_fg": 1010,
    "target_og": 1047,
    "ebc": 8,
    "srm": 4,
    "ph": 4.4,
    "attenuation_level": 79,
    },  
    {
    "id": 27,
    "name": "Bad Pixie",
    "tagline": "Spiced Wheat Beer.",
    "first_brewed": "10/2008",
    "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
    "image_url": "https://www.pokepedia.fr/images/6/66/Sabelette-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/8/8a/Miniature_027_LGPE.png",
    "abv": 4.7,
    "ibu": 45,
    "target_fg": 1010,
    "target_og": 1047,
    "ebc": 8,
    "srm": 4,
    "ph": 4.4,
    "attenuation_level": 79,
    },  
    {
    "id": 28,
    "name": "Bad Pixie",
    "tagline": "Spiced Wheat Beer.",
    "first_brewed": "10/2008",
    "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
    "image_url": "https://www.pokepedia.fr/images/a/a1/Sablaireau-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/a/a7/Miniature_028_EB.png",
    "abv": 4.7,
    "ibu": 45,
    "target_fg": 1010,
    "target_og": 1047,
    "ebc": 8,
    "srm": 4,
    "ph": 4.4,
    "attenuation_level": 79,
    },  
    {
    "id": 29,
    "name": "Bad Pixie",
    "tagline": "Spiced Wheat Beer.",
    "first_brewed": "10/2008",
    "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
    "image_url": "https://www.pokepedia.fr/images/c/ca/Nidoran♀-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/5/52/Miniature_029_LGPE.png",
    "abv": 4.7,
    "ibu": 45,
    "target_fg": 1010,
    "target_og": 1047,
    "ebc": 8,
    "srm": 4,
    "ph": 4.4,
    "attenuation_level": 79,
    },  
    {
    "id": 30,
    "name": "Bad Pixie",
    "tagline": "Spiced Wheat Beer.",
    "first_brewed": "10/2008",
    "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
    "image_url": "https://www.pokepedia.fr/images/b/b5/Nidorina-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/9/99/Miniature_030_LGPE.png",
    "abv": 4.7,
    "ibu": 45,
    "target_fg": 1010,
    "target_og": 1047,
    "ebc": 8,
    "srm": 4,
    "ph": 4.4,
    "attenuation_level": 79,
    },  
    {
    "id": 31,
    "name": "Bad Pixie",
    "tagline": "Spiced Wheat Beer.",
    "first_brewed": "10/2008",
    "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
    "image_url": "https://www.pokepedia.fr/images/7/76/Nidoqueen-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/e/e4/Miniature_031_EB.png",
    "abv": 4.7,
    "ibu": 45,
    "target_fg": 1010,
    "target_og": 1047,
    "ebc": 8,
    "srm": 4,
    "ph": 4.4,
    "attenuation_level": 79,
    },    
    {
    "id": 32,
    "name": "Nidoran",
    "tagline": "Spiced Wheat Beer.",
    "first_brewed": "10/2008",
    "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
    "image_url": "https://www.pokepedia.fr/images/8/8e/Nidoran%E2%99%82-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/f/f7/Miniature_032_LGPE.png",
    "abv": 4.7,
    "ibu": 45,
    "target_fg": 1010,
    "target_og": 1047,
    "ebc": 8,
    "srm": 4,
    "ph": 4.4,
    "attenuation_level": 79,
    },  
    {
    "id": 33,
    "name": "Nidorino",
    "tagline": "Spiced Wheat Beer.",
    "first_brewed": "10/2008",
    "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
    "image_url": "https://www.pokepedia.fr/images/f/f3/Miniature_033_LGPE.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/f/f3/Miniature_033_LGPE.png",
    "abv": 4.7,
    "ibu": 45,
    "target_fg": 1010,
    "target_og": 1047,
    "ebc": 8,
    "srm": 4,
    "ph": 4.4,
    "attenuation_level": 79,
    },  
    {
    "id": 34,
    "name": "Nidoking",
    "tagline": "Spiced Wheat Beer.",
    "first_brewed": "10/2008",
    "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
    "image_url": "https://www.pokepedia.fr/images/c/cf/Miniature_034_EB.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/c/cf/Miniature_034_EB.png",
    "abv": 4.7,
    "ibu": 45,
    "target_fg": 1010,
    "target_og": 1047,
    "ebc": 8,
    "srm": 4,
    "ph": 4.4,
    "attenuation_level": 79,
    },  
    {
    "id": 35,
    "name": "Melofée",
    "tagline": "Spiced Wheat Beer.",
    "first_brewed": "10/2008",
    "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
    "image_url": "https://www.pokepedia.fr/images/4/4d/M%C3%A9lof%C3%A9e-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/b/b8/Miniature_035_LGPE.png",
    "abv": 4.7,
    "ibu": 45,
    "target_fg": 1010,
    "target_og": 1047,
    "ebc": 8,
    "srm": 4,
    "ph": 4.4,
    "attenuation_level": 79,
    },  
    {
    "id": 36,
    "name": "Mélodelfe",
    "tagline": "Spiced Wheat Beer.",
    "first_brewed": "10/2008",
    "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
    "image_url": "https://www.pokepedia.fr/images/3/3f/M%C3%A9lodelfe-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/1/19/Miniature_036_LGPE.png",
    "abv": 4.7,
    "ibu": 45,
    "target_fg": 1010,
    "target_og": 1047,
    "ebc": 8,
    "srm": 4,
    "ph": 4.4,
    "attenuation_level": 79,
    },  
    {
    "id": 37,
    "name": "Goupix",
    "tagline": "Spiced Wheat Beer.",
    "first_brewed": "10/2008",
    "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
    "image_url": "https://www.pokepedia.fr/images/f/f6/Goupix-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/b/bb/Miniature_037_LGPE.png",
    "abv": 4.7,
    "ibu": 45,
    "target_fg": 1010,
    "target_og": 1047,
    "ebc": 8,
    "srm": 4,
    "ph": 4.4,
    "attenuation_level": 79,
    },  
    {
    "id": 38,
    "name": "Feunard",
    "tagline": "Spiced Wheat Beer.",
    "first_brewed": "10/2008",
    "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
    "image_url": "https://www.pokepedia.fr/images/0/0c/Feunard-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/b/b7/Miniature_038_EB.png",
    "abv": 4.7,
    "ibu": 45,
    "target_fg": 1010,
    "target_og": 1047,
    "ebc": 8,
    "srm": 4,
    "ph": 4.4,
    "attenuation_level": 79,
    },  
    {
    "id": 39,
    "name": "Rondoudou",
    "tagline": "Spiced Wheat Beer.",
    "first_brewed": "10/2008",
    "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
    "image_url": "https://www.pokepedia.fr/images/c/cd/Rondoudou-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/3/3e/Miniature_039_LGPE.png",
    "abv": 4.7,
    "ibu": 45,
    "target_fg": 1010,
    "target_og": 1047,
    "ebc": 8,
    "srm": 4,
    "ph": 4.4,
    "attenuation_level": 79,
    },  
    {
    "id": 40,
    "name": "Grondoudou",
    "tagline": "Spiced Wheat Beer.",
    "first_brewed": "10/2008",
    "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
    "image_url": "https://www.pokepedia.fr/images/7/7e/Grodoudou-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/1/17/Miniature_040_EB.png",
    "abv": 4.7,
    "ibu": 45,
    "target_fg": 1010,
    "target_og": 1047,
    "ebc": 8,
    "srm": 4,
    "ph": 4.4,
    "attenuation_level": 79,
    },  
    {
    "id": 41,
    "name": "Nosferapti",
    "tagline": "Spiced Wheat Beer.",
    "first_brewed": "10/2008",
    "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
    "image_url": "https://www.pokepedia.fr/images/2/2b/Nosferapti-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/1/1c/Miniature_041_LGPE.png",
    "abv": 4.7,
    "ibu": 45,
    "target_fg": 1010,
    "target_og": 1047,
    "ebc": 8,
    "srm": 4,
    "ph": 4.4,
    "attenuation_level": 79,
    },  
    {
    "id": 42,
    "name": "Nosferalto",
    "tagline": "Spiced Wheat Beer.",
    "first_brewed": "10/2008",
    "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
    "image_url": "https://www.pokepedia.fr/images/6/64/Nosferalto-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/c/c3/Miniature_042_LGPE.png",
    "abv": 4.7,
    "ibu": 45,
    "target_fg": 1010,
    "target_og": 1047,
    "ebc": 8,
    "srm": 4,
    "ph": 4.4,
    "attenuation_level": 79,
    },  
    {
    "id": 43,
    "name": "Mystherbe",
    "tagline": "Spiced Wheat Beer.",
    "first_brewed": "10/2008",
    "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
    "image_url": "https://www.pokepedia.fr/images/3/39/Mystherbe-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/7/72/Miniature_043_LGPE.png",
    "abv": 4.7,
    "ibu": 45,
    "target_fg": 1010,
    "target_og": 1047,
    "ebc": 8,
    "srm": 4,
    "ph": 4.4,
    "attenuation_level": 79,
    },  
    {
    "id": 44,
    "name": "Ortide",
    "tagline": "Spiced Wheat Beer.",
    "first_brewed": "10/2008",
    "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
    "image_url": "https://www.pokepedia.fr/images/3/39/Ortide-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/e/ec/Miniature_044_LGPE.png",
    "abv": 4.7,
    "ibu": 45,
    "target_fg": 1010,
    "target_og": 1047,
    "ebc": 8,
    "srm": 4,
    "ph": 4.4,
    "attenuation_level": 79,
    },  
    {
    "id": 45,
    "name": "Bad Pixie",
    "tagline": "Spiced Wheat Beer.",
    "first_brewed": "10/2008",
    "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
    "image_url": "https://www.pokepedia.fr/images/c/cd/Rafflesia-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/c/cb/Miniature_045_LGPE.png",
    "abv": 4.7,
    "ibu": 45,
    "target_fg": 1010,
    "target_og": 1047,
    "ebc": 8,
    "srm": 4,
    "ph": 4.4,
    "attenuation_level": 79,
    },  
    {
    "id": 46,
    "name": "Bad Pixie",
    "tagline": "Spiced Wheat Beer.",
    "first_brewed": "10/2008",
    "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
    "image_url": "https://www.pokepedia.fr/images/5/52/Paras-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/3/37/Miniature_046_LGPE.png",
    "abv": 4.7,
    "ibu": 45,
    "target_fg": 1010,
    "target_og": 1047,
    "ebc": 8,
    "srm": 4,
    "ph": 4.4,
    "attenuation_level": 79,
    },  
    {
    "id": 47,
    "name": "Bad Pixie",
    "tagline": "Spiced Wheat Beer.",
    "first_brewed": "10/2008",
    "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
    "image_url": "https://www.pokepedia.fr/images/5/55/Parasect-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/8/84/Miniature_047_LGPE.png",
    "abv": 4.7,
    "ibu": 45,
    "target_fg": 1010,
    "target_og": 1047,
    "ebc": 8,
    "srm": 4,
    "ph": 4.4,
    "attenuation_level": 79,
    },  
    {
    "id": 48,
    "name": "Bad Pixie",
    "tagline": "Spiced Wheat Beer.",
    "first_brewed": "10/2008",
    "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
    "image_url": "https://www.pokepedia.fr/images/a/a5/Mimitoss-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/c/ce/Miniature_048_LGPE.png",
    "abv": 4.7,
    "ibu": 45,
    "target_fg": 1010,
    "target_og": 1047,
    "ebc": 8,
    "srm": 4,
    "ph": 4.4,
    "attenuation_level": 79,
    },  
    {
    "id": 49,
    "name": "Bad Pixie",
    "tagline": "Spiced Wheat Beer.",
    "first_brewed": "10/2008",
    "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
    "image_url": "https://www.pokepedia.fr/images/0/0f/A%C3%A9romite-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/9/9c/Miniature_049_LGPE.png",
    "abv": 4.7,
    "ibu": 45,
    "target_fg": 1010,
    "target_og": 1047,
    "ebc": 8,
    "srm": 4,
    "ph": 4.4,
    "attenuation_level": 79,
    },  
    {
    "id": 50,
    "name": "Bad Pixie",
    "tagline": "Spiced Wheat Beer.",
    "first_brewed": "10/2008",
    "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
    "image_url": "https://www.pokepedia.fr/images/a/aa/Taupiqueur-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/0/03/Miniature_050_LGPE.png",
    "abv": 4.7,
    "ibu": 45,
    "target_fg": 1010,
    "target_og": 1047,
    "ebc": 8,
    "srm": 4,
    "ph": 4.4,
    "attenuation_level": 79,
    },  
    {
    "id": 51,
    "name": "Bad Pixie",
    "tagline": "Spiced Wheat Beer.",
    "first_brewed": "10/2008",
    "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
    "image_url": "https://www.pokepedia.fr/images/8/85/Triopikeur-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/b/b5/Miniature_051_EB.png",
    "abv": 4.7,
    "ibu": 45,
    "target_fg": 1010,
    "target_og": 1047,
    "ebc": 8,
    "srm": 4,
    "ph": 4.4,
    "attenuation_level": 79,
    },  
    {
    "id": 52,
    "name": "Bad Pixie",
    "tagline": "Spiced Wheat Beer.",
    "first_brewed": "10/2008",
    "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
    "image_url": "https://www.pokepedia.fr/images/b/b8/Miaouss-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/9/9f/Miniature_052_LGPE.png",
    "abv": 4.7,
    "ibu": 45,
    "target_fg": 1010,
    "target_og": 1047,
    "ebc": 8,
    "srm": 4,
    "ph": 4.4,
    "attenuation_level": 79,
    },  
    {
    "id": 53,
    "name": "Bad Pixie",
    "tagline": "Spiced Wheat Beer.",
    "first_brewed": "10/2008",
    "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
    "image_url": "https://www.pokepedia.fr/images/4/41/Persian-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/4/47/Miniature_053_EB.png",
    "abv": 4.7,
    "ibu": 45,
    "target_fg": 1010,
    "target_og": 1047,
    "ebc": 8,
    "srm": 4,
    "ph": 4.4,
    "attenuation_level": 79,
    },  
    {
    "id": 54,
    "name": "Bad Pixie",
    "tagline": "Spiced Wheat Beer.",
    "first_brewed": "10/2008",
    "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
    "image_url": "https://www.pokepedia.fr/images/4/44/Psykokwak-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/1/12/Miniature_054_LGPE.png",
    "abv": 4.7,
    "ibu": 45,
    "target_fg": 1010,
    "target_og": 1047,
    "ebc": 8,
    "srm": 4,
    "ph": 4.4,
    "attenuation_level": 79,
    },  
    {
    "id": 55,
    "name": "Bad Pixie",
    "tagline": "Spiced Wheat Beer.",
    "first_brewed": "10/2008",
    "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
    "image_url": "https://www.pokepedia.fr/images/6/6e/Akwakwak-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/6/6d/Miniature_055_EB.png",
    "abv": 4.7,
    "ibu": 45,
    "target_fg": 1010,
    "target_og": 1047,
    "ebc": 8,
    "srm": 4,
    "ph": 4.4,
    "attenuation_level": 79,
    },  
    {
    "id": 56,
    "name": "Bad Pixie",
    "tagline": "Spiced Wheat Beer.",
    "first_brewed": "10/2008",
    "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
    "image_url": "https://www.pokepedia.fr/images/8/8e/F%C3%A9rosinge-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/a/a3/Miniature_056_LGPE.png",
    "abv": 4.7,
    "ibu": 45,
    "target_fg": 1010,
    "target_og": 1047,
    "ebc": 8,
    "srm": 4,
    "ph": 4.4,
    "attenuation_level": 79,
    },  
    {
    "id": 57,
    "name": "Bad Pixie",
    "tagline": "Spiced Wheat Beer.",
    "first_brewed": "10/2008",
    "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
    "image_url": "https://www.pokepedia.fr/images/d/df/Colossinge-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/5/52/Miniature_057_LGPE.png",
    "abv": 4.7,
    "ibu": 45,
    "target_fg": 1010,
    "target_og": 1047,
    "ebc": 8,
    "srm": 4,
    "ph": 4.4,
    "attenuation_level": 79,
    },  
    {
    "id": 58,
    "name": "Bad Pixie",
    "tagline": "Spiced Wheat Beer.",
    "first_brewed": "10/2008",
    "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
    "image_url": "https://www.pokepedia.fr/images/e/e2/Caninos-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/7/7c/Miniature_058_LGPE.png",
    "abv": 4.7,
    "ibu": 45,
    "target_fg": 1010,
    "target_og": 1047,
    "ebc": 8,
    "srm": 4,
    "ph": 4.4,
    "attenuation_level": 79,
    },  
    {
    "id": 59,
    "name": "Bad Pixie",
    "tagline": "Spiced Wheat Beer.",
    "first_brewed": "10/2008",
    "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
    "image_url": "https://www.pokepedia.fr/images/7/7e/Arcanin-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/9/9a/Miniature_059_LGPE.png",
    "abv": 4.7,
    "ibu": 45,
    "target_fg": 1010,
    "target_og": 1047,
    "ebc": 8,
    "srm": 4,
    "ph": 4.4,
    "attenuation_level": 79,
    },  
    {
    "id": 60,
    "name": "Bad Pixie",
    "tagline": "Spiced Wheat Beer.",
    "first_brewed": "10/2008",
    "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
    "image_url": "https://www.pokepedia.fr/images/4/4b/Ptitard-RFVF.png",
    "image_logo_url" :"https://www.pokepedia.fr/images/1/12/Miniature_060_LGPE.png",
    "abv": 4.7,
    "ibu": 45,
    "target_fg": 1010,
    "target_og": 1047,
    "ebc": 8,
    "srm": 4,
    "ph": 4.4,
    "attenuation_level": 79,
    },
    {
      "id": 61,
      "name": "Bulbizarre",
      "tagline": "A Real Bitter Experience.",
      "first_brewed": "09/2007",
      "description": "A light, crisp and bitter IPA brewed with English and American hops. A small batch brewed only once.",
      "image_url": "https://www.pokepedia.fr/images/5/54/T%C3%AAtarte-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/d/da/Miniature_061_LGPE.png",
      "abv": 4.5,
      "ibu": 60,
      "target_fg": 1010,
      "target_og": 1044,
      "ebc": 20,
      "srm": 10,
      "ph": 4.4,
      "attenuation_level": 75,
      },
      {
      "id": 62,
      "name": "Herbizarre",
      "tagline": "You Know You Shouldn't",
      "first_brewed": "04/2008",
      "description": "A titillating, neurotic, peroxide punk of a Pale Ale. Combining attitude, style, substance, and a little bit of low self esteem for good measure; what would your mother say? The seductive lure of the sassy passion fruit hop proves too much to resist. All that is even before we get onto the fact that there are no additives, preservatives, pasteurization or strings attached. All wrapped up with the customary BrewDog bite and imaginative twist.",
      "image_url": "https://www.pokepedia.fr/images/3/38/Tartard-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/0/07/Miniature_062_EB.png",
      "abv": 4.1,
      "ibu": 41.5,
      "target_fg": 1010,
      "target_og": 1041.7,
      "ebc": 15,
      "srm": 15,
      "ph": 4.4,
      "attenuation_level": 76,
      },
      {
      "id": 63,
      "name": "Berliner Weisse With Yuzu - B-Sides",
      "tagline": "Japanese Citrus Berliner Weisse.",
      "first_brewed": "11/2015",
      "description": "Japanese citrus fruit intensifies the sour nature of this German classic.",
      "image_url": "https://www.pokepedia.fr/images/3/36/Abra-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/4/4b/Miniature_063_LGPE.png",
      "abv": 4.2,
      "ibu": 8,
      "target_fg": 1007,
      "target_og": 1040,
      "ebc": 8,
      "srm": 4,
      "ph": 3.2,
      "attenuation_level": 83,
      },
      {
      "id": 64,
      "name": "Pilsen Lager",
      "tagline": "Unleash the Yeast Series.",
      "first_brewed": "09/2013",
      "description": "Our Unleash the Yeast series was an epic experiment into the differences in aroma and flavour provided by switching up your yeast. We brewed up a wort with a light caramel note and some toasty biscuit flavour, and hopped it with Amarillo and Centennial for a citrusy bitterness. Everything else is down to the yeast. Pilsner yeast ferments with no fruity esters or spicy phenols, although it can add a hint of butterscotch.",
      "image_url": "https://www.pokepedia.fr/images/6/6f/Kadabra-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/e/ea/Miniature_064_LGPE.png",
      "abv": 6.3,
      "ibu": 55,
      "target_fg": 1012,
      "target_og": 1060,
      "ebc": 30,
      "srm": 15,
      "ph": 4.4,
      "attenuation_level": 80,
      },
      {
      "id": 65,
      "name": "Avery Brown Dredge",
      "tagline": "Bloggers' Imperial Pilsner.",
      "first_brewed": "02/2011",
      "description": "An Imperial Pilsner in collaboration with beer writers. Tradition. Homage. Revolution. We wanted to showcase the awesome backbone of the Czech brewing tradition, the noble Saaz hop, and also tip our hats to the modern beers that rock our world, and the people who make them.",
      "image_url": "https://www.pokepedia.fr/images/6/68/Alakazam-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/8/8f/Miniature_065_EB.png",
      "abv": 7.2,
      "ibu": 59,
      "target_fg": 1027,
      "target_og": 1069,
      "ebc": 10,
      "srm": 5,
      "ph": 4.4,
      "attenuation_level": 67,
      },
      {
      "id": 66,
      "name": "Electric India",
      "tagline": "Vibrant Hoppy Saison.",
      "first_brewed": "05/2013",
      "description": "Re-brewed as a spring seasonal, this beer – which appeared originally as an Equity Punk shareholder creation – retains its trademark spicy, fruity edge. A perfect blend of Belgian Saison and US IPA, crushed peppercorns and heather honey are also added to produce a genuinely unique beer.",
      "image_url": "https://www.pokepedia.fr/images/7/75/Machoc-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/7/7b/Miniature_066_LGPE.png",
      "abv": 5.2,
      "ibu": 38,
      "target_fg": 1005,
      "target_og": 1045,
      "ebc": 15,
      "srm": 7.5,
      "ph": 4.4,
      "attenuation_level": 88.9,
      },
      {
      "id": 67,
      "name": "AB:12",
      "tagline": "Imperial Black Belgian Ale.",
      "first_brewed": "07/2012",
      "description": "An Imperial Black Belgian Ale aged in old Invergordon Scotch whisky barrels with mountains of raspberries, tayberries and blackberries in each cask. Decadent but light and dry, this beer would make a fantastic base for ageing on pretty much any dark fruit - we used raspberries, tayberries and blackberries beause they were local.",
      "image_url": "https://www.pokepedia.fr/images/c/cf/Machopeur-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/f/f0/Miniature_067_LGPE.png",
      "abv": 11.2,
      "ibu": 35,
      "target_fg": 1017,
      "target_og": 1108,
      "ebc": 80,
      "srm": 40,
      "ph": 5.3,
      "attenuation_level": 84,
      },
      {
      "id": 68,
      "name": "Fake Lager",
      "tagline": "Bohemian Pilsner.",
      "first_brewed": "03/2013",
      "description": "Fake is the new black. Fake is where it is at. Fake Art, fake brands, fake breasts, and fake lager. We want to play our part in the ugly fallout from the Lager Dream. Say hello to Fake Lager – a zesty, floral 21st century faux masterpiece with added BrewDog bitterness.",
      "image_url": "https://www.pokepedia.fr/images/e/ee/Mackogneur-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/9/9e/Miniature_068_LGPE.png",
      "abv": 4.7,
      "ibu": 40,
      "target_fg": 1010,
      "target_og": 1046,
      "ebc": 12,
      "srm": 6,
      "ph": 4.4,
      "attenuation_level": 78,
      },
      {
      "id": 69,
      "name": "AB:07",
      "tagline": "Whisky Cask-Aged Scotch Ale.",
      "first_brewed": "03/2010",
      "description": "Whisky cask-aged imperial scotch ale. Beer perfect for when the rain is coming sideways. Liquorice, plum and raisin temper the warming alcohol, producing a beer capable of holding back the Scottish chill.",
      "image_url": "https://www.pokepedia.fr/images/f/f9/Ch%C3%A9tiflor-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/1/10/Miniature_069_LGPE.png",
      "abv": 12.5,
      "ibu": 30,
      "target_fg": 1020,
      "target_og": 1106,
      "ebc": 84,
      "srm": 42,
      "ph": 5.6,
      "attenuation_level": 83,
      },
      {
      "id": 70,
      "name": "Bramling X",
      "tagline": "Single Hop IPA Series - 2011.",
      "first_brewed": "01/2011",
      "description": "Good old Bramling Cross is elegant, refined, assured, (boring) and understated. Understated that is unless you hop the living daylights out of a beer with it. This is Bramling Cross re-invented and re-imagined, and shows just what can be done with English hops if you use enough of them. Poor Bramling Cross normally gets lost in a woeful stream of conformist brown ales made by sleepy cask ale brewers. But not anymore. This beer shows that British hops do have some soul, and is a fruity riot of blackberries, pears, and plums. Reminds me of the bramble, apple and ginger jam my grandmother used to make.",
      "image_url": "https://www.pokepedia.fr/images/f/f5/Boustiflor-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/5/5d/Miniature_070_LGPE.png",
      "abv": 7.5,
      "ibu": 75,
      "target_fg": 1013,
      "target_og": 1068,
      "ebc": 22,
      "srm": 11,
      "ph": 4.4,
      "attenuation_level": 80.9,
      },
      {
      "id": 71,
      "name": "Misspent Youth",
      "tagline": "Milk & Honey Scotch Ale.",
      "first_brewed": "04/2013",
      "description": "The brainchild of our small batch brewer, George Woods. A dangerously drinkable milk sugar- infused Scotch Ale.",
      "image_url": "https://www.pokepedia.fr/images/4/41/Empiflor-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/6/69/Miniature_071_LGPE.png",
      "abv": 7.3,
      "ibu": 30,
      "target_fg": 1020,
      "target_og": 1079,
      "ebc": 120,
      "srm": 60,
      "ph": 4.4,
      "attenuation_level": 74.7,
      },
      {
      "id": 72,
      "name": "Arcade Nation",
      "tagline": "Seasonal Black IPA.",
      "first_brewed": "12/2015",
      "description": "Running the knife-edge between an India Pale Ale and a Stout, this particular style is one we truly love. Black IPAs are a great showcase for the skill of our brew team, balancing so many complex and twisting flavours in the same moment. The citrus, mango and pine from the hops – three of our all-time favourites – play off against the roasty dryness from the malt bill at each and every turn.",
      "image_url": "https://www.pokepedia.fr/images/d/de/Tentacool-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/b/b8/Miniature_072_LGPE.png",
      "abv": 5.3,
      "ibu": 60,
      "target_fg": 1012,
      "target_og": 1052,
      "ebc": 200,
      "srm": 100,
      "ph": 4.2,
      "attenuation_level": 77,
      },
      {
      "id": 73,
      "name": "Movember",
      "tagline": "Moustache-Worthy Beer.",
      "first_brewed": "11/2009",
      "description": "A deliciously robust, black malted beer with a decadent dark, dry cocoa flavour that provides an enticing backdrop to the Cascade hops.",
      "image_url": "https://www.pokepedia.fr/images/1/1c/Tentacruel-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/5/50/Miniature_073_LGPE.png",
      "abv": 4.5,
      "ibu": 50,
      "target_fg": 1012,
      "target_og": 1047,
      "ebc": 140,
      "srm": 70,
      "ph": 5.2,
      "attenuation_level": 74.5,
      },
      {
      "id": 74,
      "name": "Alpha Dog",
      "tagline": "Existential Red Ale.",
      "first_brewed": "02/2010",
      "description": "A fusion of caramel malt flavours and punchy New Zealand hops. A session beer you can get your teeth into.",
      "image_url": "https://www.pokepedia.fr/images/b/b2/Racaillou-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/8/8d/Miniature_074_LGPE.png",
      "abv": 4.5,
      "ibu": 42,
      "target_fg": 1025,
      "target_og": 1046,
      "ebc": 62,
      "srm": 31,
      "ph": 4.4,
      "attenuation_level": 72.8,
      },
      {
      "id": 75,
      "name": "Mixtape 8",
      "tagline": "An Epic Fusion Of Old Belgian, American New Wave, And Scotch Whisky.",
      "first_brewed": "01/2012",
      "description": "This recipe is for the Belgian Tripel base. A blend of two huge oak aged beers – half a hopped up Belgian Tripel, and half a Triple India Pale Ale. Both aged in single grain whisky barrels for two years and blended, each beer brings its own character to the mix. The Belgian Tripel comes loaded with complex spicy, fruity esters, and punchy citrus hop character.",
      "image_url": "https://www.pokepedia.fr/images/a/a5/Gravalanch-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/e/e5/Miniature_075_LGPE.png",
      "abv": 14.5,
      "ibu": 50,
      "target_fg": 1014,
      "target_og": 1093,
      "ebc": 40,
      "srm": 20,
      "ph": 4.4,
      "attenuation_level": 85,
      },
      {
      "id": 76,
      "name": "Libertine Porter",
      "tagline": "Dry-Hopped Aggressive Porter.",
      "first_brewed": "01/2012",
      "description": "An avalanche of cross-continental hop varieties give this porter a complex spicy, resinous and citrusy aroma, with a huge malt bill providing a complex roasty counterpoint. Digging deeper into the flavour draws out cinder toffee, bitter chocolate and hints of woodsmoke.",
      "image_url": "https://www.pokepedia.fr/images/a/a3/Grolem-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/b/bf/Miniature_076_LGPE.png",
      "abv": 6.1,
      "ibu": 45,
      "target_fg": 1020,
      "target_og": 1067,
      "ebc": 219,
      "srm": 109.5,
      "ph": 4.4,
      "attenuation_level": 70.1,
      },
      {
      "id": 77,
      "name": "AB:06",
      "tagline": "Imperial Black IPA.",
      "first_brewed": "04/2011",
      "description": "Our sixth Abstrakt, this imperial black IPA combined dark malts with a monumental triple dry-hop, using an all-star team of some of our favourite American hops. Roasty and resinous.",
      "image_url": "https://www.pokepedia.fr/images/8/8f/Ponyta-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/e/e2/Miniature_077_LGPE.png",
      "abv": 11.2,
      "ibu": 150,
      "target_fg": 1013,
      "target_og": 1098,
      "ebc": 70,
      "srm": 35,
      "ph": null,
      "attenuation_level": 87,
      },
      {
      "id": 78,
      "name": "Russian Doll – India Pale Ale",
      "tagline": "Nesting Hop Bomb.",
      "first_brewed": "08/2014",
      "description": "The levels of hops vary throughout the range. We love hops, so all four beers are big, bitter badasses, but by tweaking the amount of each hop used later in the boil and during dry- hopping, we can balance the malty backbone with some unexpected flavours. Simcoe is used in the whirlpool for all four beers, and yet still lends different characters to each",
      "image_url": "https://www.pokepedia.fr/images/9/9c/Galopa-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/5/5d/Miniature_078_LGPE.png",
      "abv": 6,
      "ibu": 70,
      "target_fg": 1012,
      "target_og": 1058,
      "ebc": 25,
      "srm": 12.5,
      "ph": 5.2,
      "attenuation_level": 79.3,
      },
      {
      "id": 79,
      "name": "Hello My Name Is Mette-Marit",
      "tagline": "Lingonberry Double IPA.",
      "first_brewed": "06/2013",
      "description": "We sent this beer to Norway where it was known as 'Hello, my name is Censored’. You can make up your own mind as to why. This brew was a red berry explosion, with a reisnous bitter edge layered with dry berry tartness.",
      "image_url": "https://www.pokepedia.fr/images/5/5a/Ramoloss-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/f/f2/Miniature_079_LGPE.png",
      "abv": 8.2,
      "ibu": 70,
      "target_fg": 1013,
      "target_og": 1076,
      "ebc": null,
      "srm": null,
      "ph": 4.4,
      "attenuation_level": 83,
      },
      {
      "id": 80,
      "name": "Rabiator",
      "tagline": "Imperial Wheat Beer",
      "first_brewed": "03/2011",
      "description": "Imperial Wheat beer / Weizenbock brewed by a homesick German in leather trousers. Think banana bread, bubble gum and David Hasselhoff.",
      "image_url": "https://www.pokepedia.fr/images/b/b4/Flagadoss-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/1/17/Miniature_080_EB.png",
      "abv": 10.27,
      "ibu": 26,
      "target_fg": 1014,
      "target_og": 1092,
      "ebc": 24,
      "srm": 12,
      "ph": 4.4,
      "attenuation_level": 85,
      },
      {
      "id": 81,
      "name": "Vice Bier",
      "tagline": "Hoppy Wheat Bier.",
      "first_brewed": "04/2013",
      "description": "Our take on the classic German Kristallweizen. A clear German wheat beer, layers of bubblegum and vanilla perfectly balanced with the American and New Zealand hops.",
      "image_url": "https://www.pokepedia.fr/images/b/b9/Magn%C3%A9ti-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/f/fa/Miniature_081_LGPE.png",
      "abv": 4.3,
      "ibu": 25,
      "target_fg": 1010,
      "target_og": 1043,
      "ebc": 30,
      "srm": 15,
      "ph": 4,
      "attenuation_level": 81.8,
      },
      {
      "id": 82,
      "name": "Devine Rebel (w/ Mikkeller)",
      "tagline": "Oak-aged Barley Wine.",
      "first_brewed": "12/2008",
      "description": "Two of Europe's most experimental, boundary-pushing brewers, BrewDog and Mikkeller, combined forces to produce a rebellious beer that combined their respective talents and brewing skills. The 12.5% Barley Wine fermented well, and the champagne yeast drew it ever closer to 12.5%. The beer was brewed with a single hop variety and was going to be partially aged in oak casks.",
      "image_url": "https://www.pokepedia.fr/images/3/36/Magn%C3%A9ton-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/7/72/Miniature_082_EB.png",
      "abv": 12.5,
      "ibu": 100,
      "target_fg": 1030,
      "target_og": 1093,
      "ebc": 36,
      "srm": 18,
      "ph": 4.4,
      "attenuation_level": 68,
      },
      {
      "id": 83,
      "name": "Storm",
      "tagline": "Islay Whisky Aged IPA.",
      "first_brewed": "12/2007",
      "description": "Dark and powerful Islay magic infuses this tropical sensation of an IPA. Using the original Punk IPA as a base, we boosted the ABV to 8% giving it some extra backbone to stand up to the peated smoke imported directly from Islay.",
      "image_url": "https://www.pokepedia.fr/images/0/07/Canarticho-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/5/53/Miniature_083_LGPE.png",
      "abv": 8,
      "ibu": 60,
      "target_fg": 1010,
      "target_og": 1082,
      "ebc": 12,
      "srm": 6,
      "ph": 4.4,
      "attenuation_level": 86,
      },
      {
      "id": 84,
      "name": "The End Of History",
      "tagline": "The World's Strongest Beer.",
      "first_brewed": "06/2011",
      "description": "The End of History: The name derives from the famous work of philosopher Francis Fukuyama, this is to beer what democracy is to history. Complexity defined. Floral, grapefruit, caramel and cloves are intensified by boozy heat.",
      "image_url": "https://www.pokepedia.fr/images/2/2a/Doduo-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/f/fe/Miniature_084_LGPE.png",
      "abv": 55,
      "ibu": null,
      "target_fg": 1000,
      "target_og": 1112,
      "ebc": null,
      "srm": null,
      "ph": 4.4,
      "attenuation_level": 100,
      },
      {
      "id": 85,
      "name": "Bad Pixie",
      "tagline": "Spiced Wheat Beer.",
      "first_brewed": "10/2008",
      "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
      "image_url": "https://www.pokepedia.fr/images/2/2e/Dodrio-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/d/d8/Miniature_085_LGPE.png",
      "abv": 4.7,
      "ibu": 45,
      "target_fg": 1010,
      "target_og": 1047,
      "ebc": 8,
      "srm": 4,
      "ph": 4.4,
      "attenuation_level": 79,
      },
      {
      "id": 86,
      "name": "Bad Pixie",
      "tagline": "Spiced Wheat Beer.",
      "first_brewed": "10/2008",
      "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
      "image_url": "https://www.pokepedia.fr/images/3/31/Otaria-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/e/e7/Miniature_086_LGPE.png",
      "abv": 4.7,
      "ibu": 45,
      "target_fg": 1010,
      "target_og": 1047,
      "ebc": 8,
      "srm": 4,
      "ph": 4.4,
      "attenuation_level": 79,
      },  
      {
      "id": 87,
      "name": "Bad Pixie",
      "tagline": "Spiced Wheat Beer.",
      "first_brewed": "10/2008",
      "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
      "image_url": "https://www.pokepedia.fr/images/9/93/Lamantine-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/4/4d/Miniature_087_LGPE.png",
      "abv": 4.7,
      "ibu": 45,
      "target_fg": 1010,
      "target_og": 1047,
      "ebc": 8,
      "srm": 4,
      "ph": 4.4,
      "attenuation_level": 79,
      },  
      {
      "id": 88,
      "name": "Bad Pixie",
      "tagline": "Spiced Wheat Beer.",
      "first_brewed": "10/2008",
      "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
      "image_url": "https://www.pokepedia.fr/images/9/9c/Tadmorv-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/5/5d/Miniature_088_LGPE.png",
      "abv": 4.7,
      "ibu": 45,
      "target_fg": 1010,
      "target_og": 1047,
      "ebc": 8,
      "srm": 4,
      "ph": 4.4,
      "attenuation_level": 79,
      },  
      {
      "id": 89,
      "name": "Bad Pixie",
      "tagline": "Spiced Wheat Beer.",
      "first_brewed": "10/2008",
      "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
      "image_url": "https://www.pokepedia.fr/images/8/8f/Grotadmorv-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/5/53/Miniature_089_LGPE.png",
      "abv": 4.7,
      "ibu": 45,
      "target_fg": 1010,
      "target_og": 1047,
      "ebc": 8,
      "srm": 4,
      "ph": 4.4,
      "attenuation_level": 79,
      },  
      {
      "id": 90,
      "name": "Bad Pixie",
      "tagline": "Spiced Wheat Beer.",
      "first_brewed": "10/2008",
      "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
      "image_url": "https://www.pokepedia.fr/images/e/eb/Kokiyas-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/2/2e/Miniature_090_LGPE.png",
      "abv": 4.7,
      "ibu": 45,
      "target_fg": 1010,
      "target_og": 1047,
      "ebc": 8,
      "srm": 4,
      "ph": 4.4,
      "attenuation_level": 79,
      },  
      {
      "id": 91,
      "name": "Bad Pixie",
      "tagline": "Spiced Wheat Beer.",
      "first_brewed": "10/2008",
      "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
      "image_url": "https://www.pokepedia.fr/images/8/84/Crustabri-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/9/9f/Miniature_091_LGPE.png",
      "abv": 4.7,
      "ibu": 45,
      "target_fg": 1010,
      "target_og": 1047,
      "ebc": 8,
      "srm": 4,
      "ph": 4.4,
      "attenuation_level": 79,
      },    
      {
      "id": 92,
      "name": "Bad Pixie",
      "tagline": "Spiced Wheat Beer.",
      "first_brewed": "10/2008",
      "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
      "image_url": "https://www.pokepedia.fr/images/9/9f/Fantominus-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/c/cf/Miniature_092_LGPE.png",
      "abv": 4.7,
      "ibu": 45,
      "target_fg": 1010,
      "target_og": 1047,
      "ebc": 8,
      "srm": 4,
      "ph": 4.4,
      "attenuation_level": 79,
      },  
      {
      "id": 93,
      "name": "Bad Pixie",
      "tagline": "Spiced Wheat Beer.",
      "first_brewed": "10/2008",
      "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
      "image_url": "https://www.pokepedia.fr/images/0/09/Spectrum-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/1/17/Miniature_093_LGPE.png",
      "abv": 4.7,
      "ibu": 45,
      "target_fg": 1010,
      "target_og": 1047,
      "ebc": 8,
      "srm": 4,
      "ph": 4.4,
      "attenuation_level": 79,
      },  
      {
      "id": 94,
      "name": "Bad Pixie",
      "tagline": "Spiced Wheat Beer.",
      "first_brewed": "10/2008",
      "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
      "image_url": "https://www.pokepedia.fr/images/8/8d/Ectoplasma-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/2/2e/Miniature_094_LGPE.png",
      "abv": 4.7,
      "ibu": 45,
      "target_fg": 1010,
      "target_og": 1047,
      "ebc": 8,
      "srm": 4,
      "ph": 4.4,
      "attenuation_level": 79,
      },  
      {
      "id": 95,
      "name": "Bad Pixie",
      "tagline": "Spiced Wheat Beer.",
      "first_brewed": "10/2008",
      "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
      "image_url": "https://www.pokepedia.fr/images/2/24/Onix-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/4/42/Miniature_095_LGPE.png",
      "abv": 4.7,
      "ibu": 45,
      "target_fg": 1010,
      "target_og": 1047,
      "ebc": 8,
      "srm": 4,
      "ph": 4.4,
      "attenuation_level": 79,
      },  
      {
      "id": 96,
      "name": "Bad Pixie",
      "tagline": "Spiced Wheat Beer.",
      "first_brewed": "10/2008",
      "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
      "image_url": "https://www.pokepedia.fr/images/9/94/Soporifik-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/f/f6/Miniature_096_LGPE.png",
      "abv": 4.7,
      "ibu": 45,
      "target_fg": 1010,
      "target_og": 1047,
      "ebc": 8,
      "srm": 4,
      "ph": 4.4,
      "attenuation_level": 79,
      },  
      {
      "id": 97,
      "name": "Bad Pixie",
      "tagline": "Spiced Wheat Beer.",
      "first_brewed": "10/2008",
      "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
      "image_url": "https://www.pokepedia.fr/images/3/3a/Hypnomade-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/9/97/Miniature_097_LGPE.png",
      "abv": 4.7,
      "ibu": 45,
      "target_fg": 1010,
      "target_og": 1047,
      "ebc": 8,
      "srm": 4,
      "ph": 4.4,
      "attenuation_level": 79,
      },  
      {
      "id": 98,
      "name": "Bad Pixie",
      "tagline": "Spiced Wheat Beer.",
      "first_brewed": "10/2008",
      "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
      "image_url": "https://www.pokepedia.fr/images/e/ed/Krabby-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/b/b6/Miniature_098_LGPE.png",
      "abv": 4.7,
      "ibu": 45,
      "target_fg": 1010,
      "target_og": 1047,
      "ebc": 8,
      "srm": 4,
      "ph": 4.4,
      "attenuation_level": 79,
      },  
      {
      "id": 99,
      "name": "Bad Pixie",
      "tagline": "Spiced Wheat Beer.",
      "first_brewed": "10/2008",
      "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
      "image_url": "https://www.pokepedia.fr/images/5/55/Krabboss-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/f/f6/Miniature_099_LGPE.png",
      "abv": 4.7,
      "ibu": 45,
      "target_fg": 1010,
      "target_og": 1047,
      "ebc": 8,
      "srm": 4,
      "ph": 4.4,
      "attenuation_level": 79,
      },  
      {
      "id": 100,
      "name": "Bad Pixie",
      "tagline": "Spiced Wheat Beer.",
      "first_brewed": "10/2008",
      "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
      "image_url": "https://www.pokepedia.fr/images/5/59/Voltorbe-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/2/23/Miniature_100_LGPE.png",
      "abv": 4.7,
      "ibu": 45,
      "target_fg": 1010,
      "target_og": 1047,
      "ebc": 8,
      "srm": 4,
      "ph": 4.4,
      "attenuation_level": 79,
      },  
      {
      "id": 101,
      "name": "Bad Pixie",
      "tagline": "Spiced Wheat Beer.",
      "first_brewed": "10/2008",
      "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
      "image_url": "https://www.pokepedia.fr/%C3%89lectrode",
      "image_logo_url" :"https://www.pokepedia.fr/images/d/d5/Miniature_101_LGPE.png",
      "abv": 4.7,
      "ibu": 45,
      "target_fg": 1010,
      "target_og": 1047,
      "ebc": 8,
      "srm": 4,
      "ph": 4.4,
      "attenuation_level": 79,
      },  
      {
      "id": 102,
      "name": "Bad Pixie",
      "tagline": "Spiced Wheat Beer.",
      "first_brewed": "10/2008",
      "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
      "image_url": "https://www.pokepedia.fr/images/3/39/Noeunoeuf-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/5/50/Miniature_102_LGPE.png",
      "abv": 4.7,
      "ibu": 45,
      "target_fg": 1010,
      "target_og": 1047,
      "ebc": 8,
      "srm": 4,
      "ph": 4.4,
      "attenuation_level": 79,
      },  
      {
      "id": 103,
      "name": "Bad Pixie",
      "tagline": "Spiced Wheat Beer.",
      "first_brewed": "10/2008",
      "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
      "image_url": "https://www.pokepedia.fr/images/1/1f/Noadkoko-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/2/20/Miniature_103_EB.png",
      "abv": 4.7,
      "ibu": 45,
      "target_fg": 1010,
      "target_og": 1047,
      "ebc": 8,
      "srm": 4,
      "ph": 4.4,
      "attenuation_level": 79,
      },  
      {
      "id": 104,
      "name": "Bad Pixie",
      "tagline": "Spiced Wheat Beer.",
      "first_brewed": "10/2008",
      "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
      "image_url": "https://www.pokepedia.fr/images/5/58/Osselait-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/6/68/Miniature_104_LGPE.png",
      "abv": 4.7,
      "ibu": 45,
      "target_fg": 1010,
      "target_og": 1047,
      "ebc": 8,
      "srm": 4,
      "ph": 4.4,
      "attenuation_level": 79,
      },  
      {
      "id": 105,
      "name": "Bad Pixie",
      "tagline": "Spiced Wheat Beer.",
      "first_brewed": "10/2008",
      "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
      "image_url": "https://www.pokepedia.fr/images/3/39/Ossatueur-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/2/28/Miniature_105_EB.png",
      "abv": 4.7,
      "ibu": 45,
      "target_fg": 1010,
      "target_og": 1047,
      "ebc": 8,
      "srm": 4,
      "ph": 4.4,
      "attenuation_level": 79,
      },  
      {
      "id": 106,
      "name": "Bad Pixie",
      "tagline": "Spiced Wheat Beer.",
      "first_brewed": "10/2008",
      "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
      "image_url": "https://www.pokepedia.fr/images/e/e7/Kicklee-RFVF.png ",
      "image_logo_url" :"https://www.pokepedia.fr/images/0/0d/Miniature_106_LGPE.png",
      "abv": 4.7,
      "ibu": 45,
      "target_fg": 1010,
      "target_og": 1047,
      "ebc": 8,
      "srm": 4,
      "ph": 4.4,
      "attenuation_level": 79,
      },  
      {
      "id": 107,
      "name": "Bad Pixie",
      "tagline": "Spiced Wheat Beer.",
      "first_brewed": "10/2008",
      "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
      "image_url": "https://www.pokepedia.fr/images/9/9c/Tygnon-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/7/77/Miniature_107_LGPE.png",
      "abv": 4.7,
      "ibu": 45,
      "target_fg": 1010,
      "target_og": 1047,
      "ebc": 8,
      "srm": 4,
      "ph": 4.4,
      "attenuation_level": 79,
      },  
      {
      "id": 108,
      "name": "Bad Pixie",
      "tagline": "Spiced Wheat Beer.",
      "first_brewed": "10/2008",
      "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
      "image_url": "https://www.pokepedia.fr/images/7/74/Excelangue-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/6/69/Miniature_108_LGPE.png",
      "abv": 4.7,
      "ibu": 45,
      "target_fg": 1010,
      "target_og": 1047,
      "ebc": 8,
      "srm": 4,
      "ph": 4.4,
      "attenuation_level": 79,
      },  
      {
      "id": 109,
      "name": "Bad Pixie",
      "tagline": "Spiced Wheat Beer.",
      "first_brewed": "10/2008",
      "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
      "image_url": "https://www.pokepedia.fr/images/5/53/Smogo-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/f/f0/Miniature_109_LGPE.png",
      "abv": 4.7,
      "ibu": 45,
      "target_fg": 1010,
      "target_og": 1047,
      "ebc": 8,
      "srm": 4,
      "ph": 4.4,
      "attenuation_level": 79,
      },  
      {
      "id": 110,
      "name": "Bad Pixie",
      "tagline": "Spiced Wheat Beer.",
      "first_brewed": "10/2008",
      "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
      "image_url": "https://www.pokepedia.fr/images/3/38/Smogogo-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/0/03/Miniature_110_EB.png",
      "abv": 4.7,
      "ibu": 45,
      "target_fg": 1010,
      "target_og": 1047,
      "ebc": 8,
      "srm": 4,
      "ph": 4.4,
      "attenuation_level": 79,
      },  
      {
      "id": 111,
      "name": "Bad Pixie",
      "tagline": "Spiced Wheat Beer.",
      "first_brewed": "10/2008",
      "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
      "image_url": "https://www.pokepedia.fr/images/a/a1/Rhinocorne-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/2/26/Miniature_111_LGPE.png",
      "abv": 4.7,
      "ibu": 45,
      "target_fg": 1010,
      "target_og": 1047,
      "ebc": 8,
      "srm": 4,
      "ph": 4.4,
      "attenuation_level": 79,
      },  
      {
      "id": 112,
      "name": "Bad Pixie",
      "tagline": "Spiced Wheat Beer.",
      "first_brewed": "10/2008",
      "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
      "image_url": "https://www.pokepedia.fr/images/8/80/Rhinof%C3%A9ros-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/1/14/Miniature_112_LGPE.png",
      "abv": 4.7,
      "ibu": 45,
      "target_fg": 1010,
      "target_og": 1047,
      "ebc": 8,
      "srm": 4,
      "ph": 4.4,
      "attenuation_level": 79,
      },  
      {
      "id": 113,
      "name": "Bad Pixie",
      "tagline": "Spiced Wheat Beer.",
      "first_brewed": "10/2008",
      "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
      "image_url": "https://www.pokepedia.fr/images/b/b0/Leveinard-DEPS.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/3/30/Miniature_113_LGPE.png",
      "abv": 4.7,
      "ibu": 45,
      "target_fg": 1010,
      "target_og": 1047,
      "ebc": 8,
      "srm": 4,
      "ph": 4.4,
      "attenuation_level": 79,
      },  
      {
      "id": 114,
      "name": "Bad Pixie",
      "tagline": "Spiced Wheat Beer.",
      "first_brewed": "10/2008",
      "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
      "image_url": "https://www.pokepedia.fr/images/d/dc/Saquedeneu-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/1/1e/Miniature_114_LGPE.png",
      "abv": 4.7,
      "ibu": 45,
      "target_fg": 1010,
      "target_og": 1047,
      "ebc": 8,
      "srm": 4,
      "ph": 4.4,
      "attenuation_level": 79,
      },  
      {
      "id": 115,
      "name": "Bad Pixie",
      "tagline": "Spiced Wheat Beer.",
      "first_brewed": "10/2008",
      "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
      "image_url": "https://www.pokepedia.fr/images/7/78/Kangourex-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/0/07/Miniature_115_LGPE.png",
      "abv": 4.7,
      "ibu": 45,
      "target_fg": 1010,
      "target_og": 1047,
      "ebc": 8,
      "srm": 4,
      "ph": 4.4,
      "attenuation_level": 79,
      },  
      {
      "id": 116,
      "name": "Bad Pixie",
      "tagline": "Spiced Wheat Beer.",
      "first_brewed": "10/2008",
      "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
      "image_url": "https://www.pokepedia.fr/images/3/3e/Hypotrempe-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/5/52/Miniature_116_LGPE.png",
      "abv": 4.7,
      "ibu": 45,
      "target_fg": 1010,
      "target_og": 1047,
      "ebc": 8,
      "srm": 4,
      "ph": 4.4,
      "attenuation_level": 79,
      },  
      {
      "id": 117,
      "name": "Bad Pixie",
      "tagline": "Spiced Wheat Beer.",
      "first_brewed": "10/2008",
      "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
      "image_url": "https://www.pokepedia.fr/images/f/fc/Hypoc%C3%A9an-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/3/39/Miniature_117_LGPE.png",
      "abv": 4.7,
      "ibu": 45,
      "target_fg": 1010,
      "target_og": 1047,
      "ebc": 8,
      "srm": 4,
      "ph": 4.4,
      "attenuation_level": 79,
      },  
      {
      "id": 118,
      "name": "Bad Pixie",
      "tagline": "Spiced Wheat Beer.",
      "first_brewed": "10/2008",
      "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
      "image_url": "https://www.pokepedia.fr/images/1/1f/Poissir%C3%A8ne-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/e/eb/Miniature_118_LGPE.png",
      "abv": 4.7,
      "ibu": 45,
      "target_fg": 1010,
      "target_og": 1047,
      "ebc": 8,
      "srm": 4,
      "ph": 4.4,
      "attenuation_level": 79,
      },  
      {
      "id": 119,
      "name": "Bad Pixie",
      "tagline": "Spiced Wheat Beer.",
      "first_brewed": "10/2008",
      "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
      "image_url": "https://www.pokepedia.fr/images/e/ed/Poissoroy-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/e/e2/Miniature_119_LGPE.png",
      "abv": 4.7,
      "ibu": 45,
      "target_fg": 1010,
      "target_og": 1047,
      "ebc": 8,
      "srm": 4,
      "ph": 4.4,
      "attenuation_level": 79,
      },  
      {
      "id": 120,
      "name": "Bad Pixie",
      "tagline": "Spiced Wheat Beer.",
      "first_brewed": "10/2008",
      "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
      "image_url": "https://www.pokepedia.fr/images/3/34/Stari-RFVF.png",
      "image_logo_url" :"https://www.pokepedia.fr/images/e/ed/Miniature_120_LGPE.png",
      "abv": 4.7,
      "ibu": 45,
      "target_fg": 1010,
      "target_og": 1047,
      "ebc": 8,
      "srm": 4,
      "ph": 4.4,
      "attenuation_level": 79,
      },
      {
        "id": 121,
        "name": "Russian Doll – India Pale Ale",
        "tagline": "Nesting Hop Bomb.",
        "first_brewed": "08/2014",
        "description": "The levels of hops vary throughout the range. We love hops, so all four beers are big, bitter badasses, but by tweaking the amount of each hop used later in the boil and during dry- hopping, we can balance the malty backbone with some unexpected flavours. Simcoe is used in the whirlpool for all four beers, and yet still lends different characters to each",
        "image_url": "https://www.pokepedia.fr/images/8/85/Staross-RFVF.png",
        "image_logo_url" :"https://www.pokepedia.fr/images/f/f1/Miniature_121_EB.png",
        "abv": 6,
        "ibu": 70,
        "target_fg": 1012,
        "target_og": 1058,
        "ebc": 25,
        "srm": 12.5,
        "ph": 5.2,
        "attenuation_level": 79.3,
        },
        {
        "id": 122,
        "name": "Hello My Name Is Mette-Marit",
        "tagline": "Lingonberry Double IPA.",
        "first_brewed": "06/2013",
        "description": "We sent this beer to Norway where it was known as 'Hello, my name is Censored’. You can make up your own mind as to why. This brew was a red berry explosion, with a reisnous bitter edge layered with dry berry tartness.",
        "image_url": "https://www.pokepedia.fr/images/3/3b/M._Mime-RFVF.png",
        "image_logo_url" :"https://www.pokepedia.fr/images/f/f4/Miniature_122_LGPE.png",
        "abv": 8.2,
        "ibu": 70,
        "target_fg": 1013,
        "target_og": 1076,
        "ebc": null,
        "srm": null,
        "ph": 4.4,
        "attenuation_level": 83,
        },
        {
        "id": 113,
        "name": "Rabiator",
        "tagline": "Imperial Wheat Beer",
        "first_brewed": "03/2011",
        "description": "Imperial Wheat beer / Weizenbock brewed by a homesick German in leather trousers. Think banana bread, bubble gum and David Hasselhoff.",
        "image_url": "https://www.pokepedia.fr/images/a/a4/Ins%C3%A9cateur-RFVF.png",
        "image_logo_url" :"https://www.pokepedia.fr/images/6/62/Miniature_123_EB.png",
        "abv": 10.27,
        "ibu": 26,
        "target_fg": 1014,
        "target_og": 1092,
        "ebc": 24,
        "srm": 12,
        "ph": 4.4,
        "attenuation_level": 85,
        },
        {
        "id": 124,
        "name": "Vice Bier",
        "tagline": "Hoppy Wheat Bier.",
        "first_brewed": "04/2013",
        "description": "Our take on the classic German Kristallweizen. A clear German wheat beer, layers of bubblegum and vanilla perfectly balanced with the American and New Zealand hops.",
        "image_url": "https://www.pokepedia.fr/images/4/44/Lippoutou-RFVF.png",
        "image_logo_url" :"https://www.pokepedia.fr/images/2/2e/Miniature_124_EB.png",
        "abv": 4.3,
        "ibu": 25,
        "target_fg": 1010,
        "target_og": 1043,
        "ebc": 30,
        "srm": 15,
        "ph": 4,
        "attenuation_level": 81.8,
        },
        {
        "id": 125,
        "name": "Devine Rebel (w/ Mikkeller)",
        "tagline": "Oak-aged Barley Wine.",
        "first_brewed": "12/2008",
        "description": "Two of Europe's most experimental, boundary-pushing brewers, BrewDog and Mikkeller, combined forces to produce a rebellious beer that combined their respective talents and brewing skills. The 12.5% Barley Wine fermented well, and the champagne yeast drew it ever closer to 12.5%. The beer was brewed with a single hop variety and was going to be partially aged in oak casks.",
        "image_url": "https://www.pokepedia.fr/images/1/18/%C3%89lektek-RFVF.png",
        "image_logo_url" :"https://www.pokepedia.fr/images/c/c2/Miniature_125_EB.png",
        "abv": 12.5,
        "ibu": 100,
        "target_fg": 1030,
        "target_og": 1093,
        "ebc": 36,
        "srm": 18,
        "ph": 4.4,
        "attenuation_level": 68,
        },
        {
        "id": 126,
        "name": "Storm",
        "tagline": "Islay Whisky Aged IPA.",
        "first_brewed": "12/2007",
        "description": "Dark and powerful Islay magic infuses this tropical sensation of an IPA. Using the original Punk IPA as a base, we boosted the ABV to 8% giving it some extra backbone to stand up to the peated smoke imported directly from Islay.",
        "image_url": "https://www.pokepedia.fr/images/8/8d/Magmar-RFVF.png",
        "image_logo_url" :"https://www.pokepedia.fr/images/3/36/Miniature_126_EB.png",
        "abv": 8,
        "ibu": 60,
        "target_fg": 1010,
        "target_og": 1082,
        "ebc": 12,
        "srm": 6,
        "ph": 4.4,
        "attenuation_level": 86,
        },
        {
        "id": 127,
        "name": "The End Of History",
        "tagline": "The World's Strongest Beer.",
        "first_brewed": "06/2011",
        "description": "The End of History: The name derives from the famous work of philosopher Francis Fukuyama, this is to beer what democracy is to history. Complexity defined. Floral, grapefruit, caramel and cloves are intensified by boozy heat.",
        "image_url": "https://www.pokepedia.fr/images/9/92/Scarabrute-RFVF.png",
        "image_logo_url" :"https://www.pokepedia.fr/images/3/33/Miniature_127_EB.png",
        "abv": 55,
        "ibu": null,
        "target_fg": 1000,
        "target_og": 1112,
        "ebc": null,
        "srm": null,
        "ph": 4.4,
        "attenuation_level": 100,
        },
        {
        "id": 128,
        "name": "Bad Pixie",
        "tagline": "Spiced Wheat Beer.",
        "first_brewed": "10/2008",
        "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
        "image_url": "https://www.pokepedia.fr/images/4/48/Tauros-RFVF.png",
        "image_logo_url" :"https://www.pokepedia.fr/images/4/4b/Miniature_128_EB.png",
        "abv": 4.7,
        "ibu": 45,
        "target_fg": 1010,
        "target_og": 1047,
        "ebc": 8,
        "srm": 4,
        "ph": 4.4,
        "attenuation_level": 79,
        },
        {
        "id": 129,
        "name": "Bad Pixie",
        "tagline": "Spiced Wheat Beer.",
        "first_brewed": "10/2008",
        "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
        "image_url": "https://www.pokepedia.fr/images/0/06/Magicarpe-RFVF.png",
        "image_logo_url" :"https://www.pokepedia.fr/images/e/ec/Miniature_129_LGPE.png",
        "abv": 4.7,
        "ibu": 45,
        "target_fg": 1010,
        "target_og": 1047,
        "ebc": 8,
        "srm": 4,
        "ph": 4.4,
        "attenuation_level": 79,
        },  
        {
        "id": 130,
        "name": "Bad Pixie",
        "tagline": "Spiced Wheat Beer.",
        "first_brewed": "10/2008",
        "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
        "image_url": "https://www.pokepedia.fr/images/f/f2/L%C3%A9viator-RFVF.png",
        "image_logo_url" :"https://www.pokepedia.fr/images/f/f9/Miniature_130_LGPE.png",
        "abv": 4.7,
        "ibu": 45,
        "target_fg": 1010,
        "target_og": 1047,
        "ebc": 8,
        "srm": 4,
        "ph": 4.4,
        "attenuation_level": 79,
        },  
        {
        "id": 131,
        "name": "Bad Pixie",
        "tagline": "Spiced Wheat Beer.",
        "first_brewed": "10/2008",
        "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
        "image_url": "https://www.pokepedia.fr/images/4/4d/Lokhlass-RFVF.png",
        "image_logo_url" :"https://www.pokepedia.fr/images/3/35/Miniature_131_LGPE.png",
        "abv": 4.7,
        "ibu": 45,
        "target_fg": 1010,
        "target_og": 1047,
        "ebc": 8,
        "srm": 4,
        "ph": 4.4,
        "attenuation_level": 79,
        },  
        {
        "id": 132,
        "name": "Bad Pixie",
        "tagline": "Spiced Wheat Beer.",
        "first_brewed": "10/2008",
        "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
        "image_url": "https://www.pokepedia.fr/images/e/e3/M%C3%A9tamorph-RFVF.png",
        "image_logo_url" :"https://www.pokepedia.fr/images/4/48/Miniature_132_LGPE.png",
        "abv": 4.7,
        "ibu": 45,
        "target_fg": 1010,
        "target_og": 1047,
        "ebc": 8,
        "srm": 4,
        "ph": 4.4,
        "attenuation_level": 79,
        },  
        {
        "id": 133,
        "name": "Bad Pixie",
        "tagline": "Spiced Wheat Beer.",
        "first_brewed": "10/2008",
        "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
        "image_url": "https://www.pokepedia.fr/images/8/8b/%C3%89voli-RFVF.png",
        "image_logo_url" :"https://www.pokepedia.fr/images/a/a5/Miniature_133_LGPE.png",
        "abv": 4.7,
        "ibu": 45,
        "target_fg": 1010,
        "target_og": 1047,
        "ebc": 8,
        "srm": 4,
        "ph": 4.4,
        "attenuation_level": 79,
        },  
        {
        "id": 134,
        "name": "Bad Pixie",
        "tagline": "Spiced Wheat Beer.",
        "first_brewed": "10/2008",
        "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
        "image_url": "https://www.pokepedia.fr/images/6/6b/Aquali-RFVF.png",
        "image_logo_url" :"https://www.pokepedia.fr/images/4/42/Miniature_134_EB.png",
        "abv": 4.7,
        "ibu": 45,
        "target_fg": 1010,
        "target_og": 1047,
        "ebc": 8,
        "srm": 4,
        "ph": 4.4,
        "attenuation_level": 79,
        },    
        {
        "id": 135,
        "name": "Bad Pixie",
        "tagline": "Spiced Wheat Beer.",
        "first_brewed": "10/2008",
        "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
        "image_url": "https://www.pokepedia.fr/images/8/89/Voltali-RFVF.png",
        "image_logo_url" :"https://www.pokepedia.fr/images/4/46/Miniature_135_EB.png",
        "abv": 4.7,
        "ibu": 45,
        "target_fg": 1010,
        "target_og": 1047,
        "ebc": 8,
        "srm": 4,
        "ph": 4.4,
        "attenuation_level": 79,
        },  
        {
        "id": 136,
        "name": "Bad Pixie",
        "tagline": "Spiced Wheat Beer.",
        "first_brewed": "10/2008",
        "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
        "image_url": "https://www.pokepedia.fr/images/6/64/Pyroli-RFVF.png",
        "image_logo_url" :"https://www.pokepedia.fr/images/d/dd/Miniature_136_EB.png",
        "abv": 4.7,
        "ibu": 45,
        "target_fg": 1010,
        "target_og": 1047,
        "ebc": 8,
        "srm": 4,
        "ph": 4.4,
        "attenuation_level": 79,
        },  
        {
        "id": 137,
        "name": "Bad Pixie",
        "tagline": "Spiced Wheat Beer.",
        "first_brewed": "10/2008",
        "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
        "image_url": "https://www.pokepedia.fr/images/0/01/Porygon-RFVF.png",
        "image_logo_url" :"https://www.pokepedia.fr/images/1/11/Miniature_137_LGPE.png",
        "abv": 4.7,
        "ibu": 45,
        "target_fg": 1010,
        "target_og": 1047,
        "ebc": 8,
        "srm": 4,
        "ph": 4.4,
        "attenuation_level": 79,
        },  
        {
        "id": 138,
        "name": "Bad Pixie",
        "tagline": "Spiced Wheat Beer.",
        "first_brewed": "10/2008",
        "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
        "image_url": "https://www.pokepedia.fr/images/8/83/Amonita-RFVF.png",
        "image_logo_url" :"https://www.pokepedia.fr/images/f/f6/Miniature_138_LGPE.png",
        "abv": 4.7,
        "ibu": 45,
        "target_fg": 1010,
        "target_og": 1047,
        "ebc": 8,
        "srm": 4,
        "ph": 4.4,
        "attenuation_level": 79,
        },  
        {
        "id": 139,
        "name": "Bad Pixie",
        "tagline": "Spiced Wheat Beer.",
        "first_brewed": "10/2008",
        "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
        "image_url": "https://www.pokepedia.fr/images/f/f2/Amonistar-RFVF.png",
        "image_logo_url" :"https://www.pokepedia.fr/images/6/69/Miniature_139_EB.png",
        "abv": 4.7,
        "ibu": 45,
        "target_fg": 1010,
        "target_og": 1047,
        "ebc": 8,
        "srm": 4,
        "ph": 4.4,
        "attenuation_level": 79,
        },  
        {
        "id": 140,
        "name": "Bad Pixie",
        "tagline": "Spiced Wheat Beer.",
        "first_brewed": "10/2008",
        "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
        "image_url": "https://www.pokepedia.fr/images/5/57/Kabuto-RFVF.png",
        "image_logo_url" :"https://www.pokepedia.fr/images/a/a2/Miniature_140_LGPE.png	",
        "abv": 4.7,
        "ibu": 45,
        "target_fg": 1010,
        "target_og": 1047,
        "ebc": 8,
        "srm": 4,
        "ph": 4.4,
        "attenuation_level": 79,
        },  
        {
        "id": 141,
        "name": "Bad Pixie",
        "tagline": "Spiced Wheat Beer.",
        "first_brewed": "10/2008",
        "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
        "image_url": "https://www.pokepedia.fr/images/3/35/Kabutops-RFVF.png",
        "image_logo_url" :"https://www.pokepedia.fr/images/f/fb/Miniature_141_EB.png",
        "abv": 4.7,
        "ibu": 45,
        "target_fg": 1010,
        "target_og": 1047,
        "ebc": 8,
        "srm": 4,
        "ph": 4.4,
        "attenuation_level": 79,
        },  
        {
        "id": 142,
        "name": "Bad Pixie",
        "tagline": "Spiced Wheat Beer.",
        "first_brewed": "10/2008",
        "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
        "image_url": "https://www.pokepedia.fr/images/3/34/Pt%C3%A9ra-RFVF.png",
        "image_logo_url" :"https://www.pokepedia.fr/images/e/e3/Miniature_142_EB.png",
        "abv": 4.7,
        "ibu": 45,
        "target_fg": 1010,
        "target_og": 1047,
        "ebc": 8,
        "srm": 4,
        "ph": 4.4,
        "attenuation_level": 79,
        },  
        {
        "id": 143,
        "name": "Bad Pixie",
        "tagline": "Spiced Wheat Beer.",
        "first_brewed": "10/2008",
        "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
        "image_url": "https://www.pokepedia.fr/images/2/2b/Ronflex-RFVF.png",
        "image_logo_url" :"https://www.pokepedia.fr/images/8/86/Miniature_143_LGPE.png",
        "abv": 4.7,
        "ibu": 45,
        "target_fg": 1010,
        "target_og": 1047,
        "ebc": 8,
        "srm": 4,
        "ph": 4.4,
        "attenuation_level": 79,
        },  
        {
        "id": 144,
        "name": "Bad Pixie",
        "tagline": "Spiced Wheat Beer.",
        "first_brewed": "10/2008",
        "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
        "image_url": "https://www.pokepedia.fr/images/b/bb/Artikodin-RFVF.png",
        "image_logo_url" :"https://www.pokepedia.fr/images/2/2b/Miniature_144_EB.png",
        "abv": 4.7,
        "ibu": 45,
        "target_fg": 1010,
        "target_og": 1047,
        "ebc": 8,
        "srm": 4,
        "ph": 4.4,
        "attenuation_level": 79,
        },  
        {
        "id": 145,
        "name": "Bad Pixie",
        "tagline": "Spiced Wheat Beer.",
        "first_brewed": "10/2008",
        "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
        "image_url": "https://www.pokepedia.fr/images/8/81/%C3%89lecthor-RFVF.png",
        "image_logo_url" :"https://www.pokepedia.fr/images/c/c7/Miniature_145_EB.png",
        "abv": 4.7,
        "ibu": 45,
        "target_fg": 1010,
        "target_og": 1047,
        "ebc": 8,
        "srm": 4,
        "ph": 4.4,
        "attenuation_level": 79,
        },  
        {
        "id": 146,
        "name": "Bad Pixie",
        "tagline": "Spiced Wheat Beer.",
        "first_brewed": "10/2008",
        "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
        "image_url": "https://www.pokepedia.fr/images/d/db/Sulfura-DEPS.png",
        "image_logo_url" :"https://www.pokepedia.fr/images/d/df/Miniature_146_EB.png",
        "abv": 4.7,
        "ibu": 45,
        "target_fg": 1010,
        "target_og": 1047,
        "ebc": 8,
        "srm": 4,
        "ph": 4.4,
        "attenuation_level": 79,
        },  
        {
        "id": 147,
        "name": "Bad Pixie",
        "tagline": "Spiced Wheat Beer.",
        "first_brewed": "10/2008",
        "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
        "image_url": "https://www.pokepedia.fr/images/1/11/Minidraco-RFVF.png",
        "image_logo_url" :"https://www.pokepedia.fr/images/b/b4/Miniature_147_LGPE.png",
        "abv": 4.7,
        "ibu": 45,
        "target_fg": 1010,
        "target_og": 1047,
        "ebc": 8,
        "srm": 4,
        "ph": 4.4,
        "attenuation_level": 79,
        },  
        {
        "id": 148,
        "name": "Bad Pixie",
        "tagline": "Spiced Wheat Beer.",
        "first_brewed": "10/2008",
        "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
        "image_url": "https://www.pokepedia.fr/images/d/d1/Draco-RFVF.png",
        "image_logo_url" :"https://www.pokepedia.fr/images/d/df/Miniature_148_LGPE.png",
        "abv": 4.7,
        "ibu": 45,
        "target_fg": 1010,
        "target_og": 1047,
        "ebc": 8,
        "srm": 4,
        "ph": 4.4,
        "attenuation_level": 79,
        },  
        {
        "id": 149,
        "name": "Bad Pixie",
        "tagline": "Spiced Wheat Beer.",
        "first_brewed": "10/2008",
        "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
        "image_url": "https://www.pokepedia.fr/images/8/87/Dracolosse-RFVF.png",
        "image_logo_url" :"https://www.pokepedia.fr/images/8/81/Miniature_149_LGPE.png",
        "abv": 4.7,
        "ibu": 45,
        "target_fg": 1010,
        "target_og": 1047,
        "ebc": 8,
        "srm": 4,
        "ph": 4.4,
        "attenuation_level": 79,
        },  
        {
        "id": 150,
        "name": "Bad Pixie",
        "tagline": "Spiced Wheat Beer.",
        "first_brewed": "10/2008",
        "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
        "image_url": "https://www.pokepedia.fr/images/d/d8/Mewtwo-DEPS.png",
        "image_logo_url" :"https://www.pokepedia.fr/images/c/cc/Miniature_150_LGPE.png",
        "abv": 4.7,
        "ibu": 45,
        "target_fg": 1010,
        "target_og": 1047,
        "ebc": 8,
        "srm": 4,
        "ph": 4.4,
        "attenuation_level": 79,
        },  
        {
        "id": 151,
        "name": "Bad Pixie",
        "tagline": "Spiced Wheat Beer.",
        "first_brewed": "10/2008",
        "description": "2008 Prototype beer, a 4.7% wheat ale with crushed juniper berries and citrus peel.",
        "image_url": "https://www.pokepedia.fr/images/1/16/Mew-DEPS.png",
        "image_logo_url" :"https://www.pokepedia.fr/images/1/12/Miniature_151_LGPE.png",
        "abv": 4.7,
        "ibu": 45,
        "target_fg": 1010,
        "target_og": 1047,
        "ebc": 8,
        "srm": 4,
        "ph": 4.4,
        "attenuation_level": 79,
        },  
  ]

  getBookId(parameter : number){
    return  this.pokemon.find(element => element.id == parameter);
  }
}
